recipe: default.v1
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: LogisticRegressionClassifier
    max_iter: 500 
  - name: NLUCommandAdapter
    user_input:
      max_characters: 420
  - name: SingleStepLLMCommandGenerator
    llm:
      model_group: openai-direct-gpt-4
    flow_retrieval:
      active: false
    prompt_template: prompts/command-generator.jinja2

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    model_group: openai-direct-gpt-4

assistant_id: 20250226-101111-delicious-dimension
