recipe: default.v1
language: en
pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: openai-direct-gpt-4o
    flow_retrieval:
      active: false
    prompt_template: prompts/command-generator.jinja2

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    model_group: openai-direct-gpt-4o

assistant_id: 20250226-101111-delicious-dimension
