recipe: default.v1
language: en
# Unique identifier for your assistant that helps differentiate between multiple deployed assistants (Required).
assistant_id: 20250226-101111-delicious-dimension

# The pipeline lists the components that process the latest user message and produce commands for the conversation (Required).
pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: openai-direct-gpt-4o

# The policies list the dialogue policies your assistant will use to progress the conversation (FlowPolicy required for CALM).
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    model_group: gpt-4o-mini
